import Mathlib

/-!
# Ring-theoretic consequences of the factorization property

This file formalizes the implicit implications of Section 5
("Ring-Theoretic Consequences") of the paper *Integer Coefficients Power Series
with Prescribed Zero Sets* by Jon Bannon and David Feldman, contained in the
paragraph beginning "The key algebraic consequence of Theorem `prop:Zi` is that
every element of `𝒪(𝔻)` is divisible by an element of `ℛ` up to a unit.
Corollary `cor:ideals` and Proposition `prop:inject` flow directly from this."

The paper deduces these two results purely formally from the factorization
statement of Proposition "Factorization up to units in `𝒪(𝔻)`" (`prop:associate`),
which itself rests on the not-yet-formalized Gaussian-integer realization
theorem (`prop:Zi`). We therefore isolate the factorization statement as an
explicit *hypothesis* on an abstract commutative ring `O` with a subring `R`
(playing the roles of `𝒪(𝔻)` and `ℛ`), and prove the two consequences from it.
When the realization theorem is confirmed and the factorization property is
established for the concrete `𝒪(𝔻)` and `ℛ`, these results become immediately
available by instantiation.

Concretely, writing `R.subtype : R →+* O` for the inclusion, the contraction
of an ideal `I : Ideal O` is `I.comap R.subtype : Ideal R` (the paper's
`I ∩ ℛ`), and its extension back to `O` is `(I.comap R.subtype).map R.subtype`
(the paper's `(I ∩ ℛ)·𝒪(𝔻)`).

We prove:
* `RequestProject.ideal_eq_map_comap` — Corollary `cor:ideals`:
  every ideal `I` of `O` equals `(I ∩ R)·O`.
* `RequestProject.comap_subtype_injective` — the contraction map `I ↦ I ∩ R`
  is injective on *all* ideals of `O`. This is stronger than the paper's
  Proposition `prop:inject`, whose proof uses maximality; the factorization
  property alone forces it for arbitrary ideals.
* `RequestProject.contraction_maximalSpec_injective` — Proposition `prop:inject`:
  the paper's contraction map `φ : MaxSpec(𝒪(𝔻)) → Spec(ℛ)`, `𝔪 ↦ 𝔪 ∩ ℛ`, is
  injective (specialization of the previous item to maximal ideals).
* `RequestProject.contract_ne_bot` — the well-definedness observation used in
  Section 5 that the contraction of a nonzero ideal is nonzero.
-/

namespace RequestProject

section RingConsequences

variable {O : Type*} [CommRing O] (R : Subring O)

/-- The factorization property of Proposition `prop:associate` ("Factorization up
to units in `𝒪(𝔻)`"): every element of `O` is an element of the subring `R`
times a unit of `O`. In the paper this is the statement that every `f ∈ 𝒪(𝔻)`
can be written `f = g · u` with `g ∈ ℛ` and `u ∈ 𝒪(𝔻)ˣ`. -/
def HasSubringFactorization : Prop :=
  ∀ f : O, ∃ g : O, g ∈ R ∧ ∃ u : Oˣ, f = g * (u : O)

variable {R}

/-- **Corollary `cor:ideals`.** Assuming the factorization property, every ideal
`I` of `O` is generated by its elements lying in `R`; that is,
`I = (I ∩ R)·O`, expressed here as `I = (I.comap R.subtype).map R.subtype`. -/
theorem ideal_eq_map_comap (hfact : HasSubringFactorization R)
    (I : Ideal O) : I = (I.comap R.subtype).map R.subtype := by
  refine' le_antisymm _ _
  · intro f hf
    obtain ⟨g, hgR, u, hgu⟩ := hfact f
    convert Ideal.mul_mem_right _ _
      (Ideal.mem_map_of_mem _ (show ⟨g, hgR⟩ ∈ I.comap R.subtype from ?_)) using 1
    convert hgu
    · infer_instance
    · simpa [hgu] using I.mul_mem_right (↑u⁻¹) hf
  · exact Ideal.map_comap_le

/-- The contraction map `I ↦ I ∩ R` (i.e. `I ↦ I.comap R.subtype`) is injective
on **all** ideals of `O`, assuming the factorization property. This is stronger
than the paper's Proposition `prop:inject` (which restricts to maximal ideals and
uses maximality in its proof): under the factorization property the two
inclusions `m ⊆ m'` and `m' ⊆ m` both follow directly. -/
theorem comap_subtype_injective (hfact : HasSubringFactorization R)
    {m m' : Ideal O} (h : m.comap R.subtype = m'.comap R.subtype) : m = m' := by
  refine le_antisymm ?_ ?_
  · intro x hx
    obtain ⟨g, hg, u, rfl⟩ := hfact x
    replace h := SetLike.ext_iff.mp h ⟨g, hg⟩
    aesop
  · intro x hx
    obtain ⟨g, hgR, u, rfl⟩ := hfact x
    simp_all +decide
    replace h := SetLike.ext_iff.mp h ⟨g, hgR⟩
    aesop

/-- **Proposition `prop:inject`.** Assuming the factorization property, the
paper's contraction map `φ : MaxSpec(𝒪(𝔻)) → Spec(ℛ)`, `𝔪 ↦ 𝔪 ∩ ℛ`, is
injective. Here `MaxSpec(𝒪(𝔻))` is modelled by the subtype of maximal ideals of
`O` and the map sends `𝔪` to its contraction `𝔪.comap R.subtype`. -/
theorem contraction_maximalSpec_injective (hfact : HasSubringFactorization R) :
    Function.Injective
      (fun m : {m : Ideal O // m.IsMaximal} => m.1.comap R.subtype) := by
  intro m m' h
  exact Subtype.ext (comap_subtype_injective hfact h)

/-- Well-definedness of the contraction map into `Spec R` (used implicitly in
Section 5): assuming the factorization property, the contraction of a nonzero
ideal of `O` is a nonzero ideal of `R`. -/
theorem contract_ne_bot (hfact : HasSubringFactorization R)
    {I : Ideal O} (hI : I ≠ ⊥) : I.comap R.subtype ≠ ⊥ := by
  simp_all +decide [Submodule.eq_bot_iff]
  obtain ⟨x, hxI, hx⟩ := hI
  obtain ⟨g, hgR, u, rfl⟩ := hfact x
  use g
  aesop

end RingConsequences

end RequestProject
